
### index
GET http://localhost:3000/songs


### show
GET http://localhost:3000/songs/3


### create
POST  http://localhost:3000/songs
Content-Type: application/json

{
    "title": "title create",
    "album": "album create",
    "artist": "artist create",
    "year": "year create"
}

### update
PATCH http://localhost:3000/songs/4
Content-Type: application/json

{
    "title": "title update",
    "album": "album update",
    "artist": "artist update",
    "year": "year update"
}

### destroy
DELETE http://localhost:3000/songs/5